### ISSUE TITLE
xbuild error

### ISSUE THREAD

**Issue by Sunshadow99** [cypherkey/RaspberryPi.Net#27]
Compiling "xbuild RaspberryPiDotNet.csproj" isn't working with the  Mono Version 3.2.8.0, XBuild Engine 12.0

Error message:

Project "/home/pi/dev/RaspberryPi.Net/RaspberryPiDotNet/RaspberryPiDotNet.csproj" (default target(s)):
        Target PrepareForBuild:
                Configuration: Debug Platform: AnyCPU
        Target GenerateSatelliteAssemblies:
        No input files were specified for target GenerateSatelliteAssemblies, skipping.
        Target GenerateTargetFrameworkMonikerAttribute:
        Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
        Target CoreCompile:
                Tool /usr/bin/dmcs execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/RaspberryPiDotNet.dll DS1620.cs GPIO.cs GPIODebug.cs GPIODirection.cs GPIOFile.cs GPIOMem.cs GPIOPins.cs GPIOResistor.cs MCP3008.cs MicroLiquidCrystal/RaspPiGPIOFileLcdTransferProvider.cs MicroLiquidCrystal/RaspPiGPIOMemLcdTransferProvider.cs MicroLiquidCrystal/ILcdTransferProvider.cs MicroLiquidCrystal/Lcd.cs PinState.cs Properties/AssemblyInfo.cs TM16XX/TM1638.cs TM16XX/TM16XX.cs /target:library /define:"DEBUG;TRACE" /doc:bin/Debug/RaspberryPiDotNet.XML /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Core.dll /warn:4
DS1620.cs(92,42): error CS0589: Internal compiler error during parsingSystem.FormatException: Input string was not in the correct format
                  at System.Double.Parse (System.String s, NumberStyles style, IFormatProvider provider) [0x00000] in <filename unknown>:0
                  at Mono.CSharp.Tokenizer.adjust_real (TypeCode t, Location loc) [0x00000] in <filename unknown>:0
                  at Mono.CSharp.Tokenizer.is_number (Int32 c, Boolean dotLead) [0x00000] in <filename unknown>:0
                  at Mono.CSharp.Tokenizer.xtoken () [0x00000] in <filename unknown>:0
                  at Mono.CSharp.Tokenizer.token () [0x00000] in <filename unknown>:0
                  at Mono.CSharp.CSharpParser.yyparse (yyInput yyLex) [0x00000] in <filename unknown>:0
                  at Mono.CSharp.CSharpParser.parse () [0x00000] in <filename unknown>:0
        Task "Csc" execution -- FAILED
        Done building target "CoreCompile" in project "/home/pi/dev/RaspberryPi.Net/RaspberryPiDotNet/RaspberryPiDotNet.csproj".-- FAILED
Done building project "/home/pi/dev/RaspberryPi.Net/RaspberryPiDotNet/RaspberryPiDotNet.csproj".-- FAILED

Build FAILED.
Errors:

/home/pi/dev/RaspberryPi.Net/RaspberryPiDotNet/RaspberryPiDotNet.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

        DS1620.cs(92,42): error CS0589: Internal compiler error during parsingSystem.FormatException: Input string was not in the correct format

         0 Warning(s)
         1 Error(s)

**Comment by derphilipp** [comment]
First guess: You are German:

I had my locale set to `de_DE.UTF8` and had the same problem;
Changing it to `en_GB.UTF-8` plus logout/login fixed it for me.

I guess because German writes float values (i.e. 3.154) with a comma (i.e. 3,154) which seems to have an influence on the mono compiler;

If that does not help: Update your firmare by:
`sudo rpi-update`
`sudo reboot`

After a reboot the compile should work!

**Comment by brunoamancio** [comment]
@Sunshadow99 , please, download my fork on https://github.com/brunoamancio/RaspberryPi.Net and try it. Here is the change: https://github.com/brunoamancio/RaspberryPi.Net/commit/c20fb112207868f00140087596846435b5217d64

Don't forget to tell the results.

**Comment by ffischer1984** [comment]
I had in this project a string parsing-problem and the Project from brunoamancio worked!

**Comment by Suchtaaa** [comment]
Hello, i get 31 Error.
The Step from brunoamncio doesn't work...

It's says everytime that it has an error in CS0518 'The predefined type [...] is not defined or imported'.
